spring:
  application:
    name: sailing-app
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/sailing-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: none